### ISSUE TITLE
Android compilation fail

### ISSUE THREAD

**Issue by antlafarge** [OculusVR/RakNet#66]
Hello, when I try to build RakNet for Android with cygwin, I get this error :

```
jni/RakNetSources/FileList.cpp:18:20: fatal error: asm/io.h: No such file or directory
 #include <asm/io.h>
```

**Comment by larku** [comment]
If I remember correctly I simply commented out/removed this include.

**Comment by antlafarge** [comment]
Okay well, now I get this error.

```
jni/RakNetSources/RandSync.cpp:13:18: fatal error: limits: No such file or directory
 #include <limits>
```

**Comment by antlafarge** [comment]
Okay I managed to build RakNet adding my `APP_STL := stlport_static` in Application.mk (add the STL).

**Comment by ankurgupta7** [comment]
Thanks for the pointer. Though I solved it with 
`APP_STL := c++_static`

**Comment by lizijie** [comment]
@ankurgupta7 not work for me
